from datetime import datetime, timezone
from html import escape
import json
import sys


response_path, manifest_path, output_path, http_status = sys.argv[1:]
with open(response_path, encoding="utf-8") as source:
    response = json.load(source)
with open(manifest_path, encoding="utf-8") as source:
    manifest = source.read()

evidence = response.get("evidence", {})
evaluation = response.get("evaluation", {})
violations = response.get("violations", [])
accepted = response.get("conforms") is True and str(http_status) == "200"
status_text = "ACCEPTED" if accepted else "REJECTED"
decision = "PROCEEDS" if accepted else "SKIPPED"
build = escape(__import__("os").environ.get("BUILD_TAG", "local"))

def block(value):
    return f"<pre>{escape(value or '(none)')}</pre>"

policy_html = ""
for policy in evaluation.get("policies", []):
    policy_html += (
        f"<h3>{escape(policy.get('code', ''))}</h3>"
        f"<p><strong>Source shape:</strong> <code>{escape(policy.get('sourceShape', ''))}</code><br>"
        f"<strong>Label:</strong> {escape(policy.get('label', ''))}</p>"
        f"<p>{escape(policy.get('message', ''))}</p>"
        f"<details><summary>SHACL SPARQL constraint</summary>{block(policy.get('sparql', ''))}</details>"
    )

violations_html = "<p>No SHACL violations.</p>"
if violations:
    rows = "".join(
        "<tr>" + "".join(f"<td>{escape(str(item.get(key) or ''))}</td>" for key in ("code", "severity", "source", "target", "sourceDomain", "targetDomain", "message")) + "</tr>"
        for item in violations
    )
    violations_html = "<table><tr><th>Code</th><th>Severity</th><th>Source</th><th>Target</th><th>Source domain</th><th>Target domain</th><th>Message</th></tr>" + rows + "</table>"

html = f"""<!doctype html>
<html><head><meta charset="utf-8"><title>Architecture Assertion Report - {escape(response.get('assertionId', ''))}</title>
<style>body{{font:15px system-ui, sans-serif;max-width:1200px;margin:2rem auto;padding:0 1rem;color:#202124}} h1{{margin-bottom:.2rem}} h2{{border-bottom:1px solid #ddd;padding-bottom:.35rem;margin-top:2rem}} pre{{background:#f5f7f9;border:1px solid #dfe3e8;border-radius:4px;padding:1rem;overflow:auto;white-space:pre-wrap}} .status{{font-weight:700;color:{'#137333' if accepted else '#b3261e'}}} table{{border-collapse:collapse;width:100%;font-size:13px}} th,td{{border:1px solid #ddd;padding:.45rem;text-align:left;vertical-align:top}} th{{background:#f1f3f4}} code{{word-break:break-all}}</style></head>
<body><h1>Architecture Assertion Report</h1>
<p><strong>Assertion:</strong> {escape(response.get('assertionId', ''))}<br><strong>Build:</strong> {build}<br><strong>Generated:</strong> {datetime.now(timezone.utc).isoformat()}</p>
<p class="status">ARCHITECTURE ASSERTION: {status_text}</p>
<p><strong>API response:</strong> HTTP {escape(str(http_status))}<br><strong>SHACL conforms:</strong> {escape(str(response.get('conforms')).lower())}</p>

<h2>1. Deployment Manifest</h2>{block(manifest)}
<h2>2. Candidate RDF</h2><p>Candidate RDF generated by the Assertion API and used in SHACL evaluation.</p>{block(evidence.get('candidateRdf'))}
<h2>3. Authoritative RDF Context</h2><p>Authoritative context retrieved from Fuseki for this evaluation.</p>{block(evidence.get('authoritativeContextRdf'))}
<h2>4. Architecture Policy</h2><p><strong>Policy codes evaluated:</strong> {escape(', '.join(evaluation.get('policyCodes', [])) or '(none)')}</p>{policy_html}
<h2>5. SHACL Evaluation</h2><p>The following is the human-readable interpretation of the actual SHACL result.</p>{violations_html}<details><summary>Raw SHACL validation report RDF</summary>{block(evidence.get('shaclReportRdf'))}</details>
<h2>6. Deployment Decision</h2><p class="status">ARCHITECTURE ASSERTION: {status_text}</p><p><strong>Jenkins deployment gate:</strong> {'PASSED' if accepted else 'FAILED'}<br><strong>Deployment:</strong> {decision}</p>
</body></html>"""

with open(output_path, "w", encoding="utf-8") as output:
    output.write(html)
